// Code generated by protoc-gen-go.
// source: pop.proto
// DO NOT EDIT!

/*
Package pop is a generated protocol buffer package.

It is generated from these files:
	pop.proto

It has these top-level messages:
	Container
	ContainerList
	Credentials
	Endpoint
	Filter
	Image
	IpConfig
	Token
*/
package pop

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Container struct {
	Id             string               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Names          []string             `protobuf:"bytes,2,rep,name=names" json:"names,omitempty"`
	ImageId        string               `protobuf:"bytes,3,opt,name=image_id,json=imageId" json:"image_id,omitempty"`
	Command        string               `protobuf:"bytes,4,opt,name=command" json:"command,omitempty"`
	Created        int64                `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	Status         string               `protobuf:"bytes,6,opt,name=status" json:"status,omitempty"`
	ExtendedStatus string               `protobuf:"bytes,7,opt,name=extended_status,json=extendedStatus" json:"extended_status,omitempty"`
	Endpoints      map[string]*Endpoint `protobuf:"bytes,8,rep,name=endpoints" json:"endpoints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Container) Reset()                    { *m = Container{} }
func (m *Container) String() string            { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()               {}
func (*Container) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *Container) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *Container) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Container) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Container) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Container) GetExtendedStatus() string {
	if m != nil {
		return m.ExtendedStatus
	}
	return ""
}

func (m *Container) GetEndpoints() map[string]*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type ContainerList struct {
	List []*Container `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *ContainerList) Reset()                    { *m = ContainerList{} }
func (m *ContainerList) String() string            { return proto.CompactTextString(m) }
func (*ContainerList) ProtoMessage()               {}
func (*ContainerList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ContainerList) GetList() []*Container {
	if m != nil {
		return m.List
	}
	return nil
}

// Credentials represents the login credentials for a given user.
type Credentials struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *Credentials) Reset()                    { *m = Credentials{} }
func (m *Credentials) String() string            { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()               {}
func (*Credentials) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Endpoint struct {
	NetId      string    `protobuf:"bytes,1,opt,name=net_id,json=netId" json:"net_id,omitempty"`
	EndpointId string    `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId" json:"endpoint_id,omitempty"`
	Ipv4       *IpConfig `protobuf:"bytes,3,opt,name=ipv4" json:"ipv4,omitempty"`
	Ipv6       *IpConfig `protobuf:"bytes,4,opt,name=ipv6" json:"ipv6,omitempty"`
	Mac        string    `protobuf:"bytes,5,opt,name=mac" json:"mac,omitempty"`
}

func (m *Endpoint) Reset()                    { *m = Endpoint{} }
func (m *Endpoint) String() string            { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()               {}
func (*Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Endpoint) GetNetId() string {
	if m != nil {
		return m.NetId
	}
	return ""
}

func (m *Endpoint) GetEndpointId() string {
	if m != nil {
		return m.EndpointId
	}
	return ""
}

func (m *Endpoint) GetIpv4() *IpConfig {
	if m != nil {
		return m.Ipv4
	}
	return nil
}

func (m *Endpoint) GetIpv6() *IpConfig {
	if m != nil {
		return m.Ipv6
	}
	return nil
}

func (m *Endpoint) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

type Filter struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Filter) Reset()                    { *m = Filter{} }
func (m *Filter) String() string            { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()               {}
func (*Filter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Filter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Image struct {
}

func (m *Image) Reset()                    { *m = Image{} }
func (m *Image) String() string            { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()               {}
func (*Image) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type IpConfig struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Gateway string `protobuf:"bytes,2,opt,name=gateway" json:"gateway,omitempty"`
	Prefix  int64  `protobuf:"varint,3,opt,name=prefix" json:"prefix,omitempty"`
}

func (m *IpConfig) Reset()                    { *m = IpConfig{} }
func (m *IpConfig) String() string            { return proto.CompactTextString(m) }
func (*IpConfig) ProtoMessage()               {}
func (*IpConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *IpConfig) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *IpConfig) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *IpConfig) GetPrefix() int64 {
	if m != nil {
		return m.Prefix
	}
	return 0
}

// Token is a token generated by the server after a successful login.
// This token should be set as metadata, to authenticate every other
type Token struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Token) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Container)(nil), "pop.Container")
	proto.RegisterType((*ContainerList)(nil), "pop.ContainerList")
	proto.RegisterType((*Credentials)(nil), "pop.Credentials")
	proto.RegisterType((*Endpoint)(nil), "pop.Endpoint")
	proto.RegisterType((*Filter)(nil), "pop.Filter")
	proto.RegisterType((*Image)(nil), "pop.Image")
	proto.RegisterType((*IpConfig)(nil), "pop.IpConfig")
	proto.RegisterType((*Token)(nil), "pop.Token")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PoP service

type PoPClient interface {
	Containers(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*ContainerList, error)
	// Login logs an user in and sets up a session.
	// The returned token should be set into the metadata
	// of the gRPC session with key "token" to authenticate your client.
	Login(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*Token, error)
	// Logout invalids the current token.
	Logout(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type poPClient struct {
	cc *grpc.ClientConn
}

func NewPoPClient(cc *grpc.ClientConn) PoPClient {
	return &poPClient{cc}
}

func (c *poPClient) Containers(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*ContainerList, error) {
	out := new(ContainerList)
	err := grpc.Invoke(ctx, "/pop.PoP/Containers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poPClient) Login(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := grpc.Invoke(ctx, "/pop.PoP/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poPClient) Logout(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/pop.PoP/Logout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PoP service

type PoPServer interface {
	Containers(context.Context, *Filter) (*ContainerList, error)
	// Login logs an user in and sets up a session.
	// The returned token should be set into the metadata
	// of the gRPC session with key "token" to authenticate your client.
	Login(context.Context, *Credentials) (*Token, error)
	// Logout invalids the current token.
	Logout(context.Context, *google_protobuf.Empty) (*google_protobuf.Empty, error)
}

func RegisterPoPServer(s *grpc.Server, srv PoPServer) {
	s.RegisterService(&_PoP_serviceDesc, srv)
}

func _PoP_Containers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoPServer).Containers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pop.PoP/Containers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoPServer).Containers(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoP_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoPServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pop.PoP/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoPServer).Login(ctx, req.(*Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoP_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoPServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pop.PoP/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoPServer).Logout(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _PoP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pop.PoP",
	HandlerType: (*PoPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Containers",
			Handler:    _PoP_Containers_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _PoP_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _PoP_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pop.proto",
}

func init() { proto.RegisterFile("pop.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x53, 0x51, 0x6b, 0xdb, 0x3c,
	0x14, 0xad, 0xed, 0xd8, 0x89, 0xaf, 0x69, 0xbe, 0x22, 0xbe, 0x15, 0xcf, 0x50, 0x96, 0x79, 0x0f,
	0xcd, 0xcb, 0xf2, 0x90, 0x8e, 0x32, 0xba, 0xc7, 0x90, 0x41, 0x58, 0x1e, 0x8a, 0x37, 0xf6, 0x1a,
	0xd4, 0xea, 0xc6, 0x88, 0xc6, 0x92, 0xb1, 0x94, 0xb6, 0xf9, 0x29, 0xdb, 0x5f, 0xda, 0x9f, 0x1a,
	0x92, 0x2d, 0x97, 0xb0, 0xed, 0xcd, 0xe7, 0x9e, 0x63, 0xe9, 0xdc, 0x7b, 0xae, 0x20, 0xae, 0x65,
	0x3d, 0xab, 0x1b, 0xa9, 0x25, 0x09, 0x6a, 0x59, 0x67, 0x09, 0x56, 0xb5, 0x3e, 0xb4, 0x95, 0xfc,
	0x97, 0x0f, 0xf1, 0x42, 0x0a, 0x4d, 0xb9, 0xc0, 0x86, 0x8c, 0xc1, 0xe7, 0x2c, 0xf5, 0x26, 0xde,
	0x34, 0x2e, 0x7c, 0xce, 0xc8, 0xff, 0x10, 0x0a, 0x5a, 0xa1, 0x4a, 0xfd, 0x49, 0x30, 0x8d, 0x8b,
	0x16, 0x90, 0xd7, 0x30, 0xe2, 0x15, 0x2d, 0x71, 0xc3, 0x59, 0x1a, 0x58, 0xed, 0xd0, 0xe2, 0x15,
	0x23, 0x29, 0x0c, 0xef, 0x65, 0x55, 0x51, 0xc1, 0xd2, 0x41, 0xcb, 0x74, 0xd0, 0x32, 0x0d, 0x52,
	0x8d, 0x2c, 0x0d, 0x27, 0xde, 0x34, 0x28, 0x1c, 0x24, 0xe7, 0x10, 0x29, 0x4d, 0xf5, 0x5e, 0xa5,
	0x91, 0xfd, 0xa5, 0x43, 0xe4, 0x12, 0xfe, 0xc3, 0x67, 0x8d, 0x82, 0x21, 0xdb, 0x74, 0x82, 0xa1,
	0x15, 0x8c, 0x5d, 0xf9, 0x6b, 0x2b, 0xfc, 0x04, 0x31, 0x0a, 0x56, 0x4b, 0x2e, 0xb4, 0x4a, 0x47,
	0x93, 0x60, 0x9a, 0xcc, 0x2f, 0x66, 0xa6, 0xe9, 0xbe, 0xb1, 0xd9, 0xd2, 0xf1, 0x4b, 0xa1, 0x9b,
	0x43, 0xf1, 0xa2, 0xcf, 0xbe, 0xc0, 0xf8, 0x98, 0x24, 0x67, 0x10, 0x3c, 0xe0, 0xa1, 0x9b, 0x82,
	0xf9, 0x24, 0xef, 0x20, 0x7c, 0xa4, 0xbb, 0x3d, 0xa6, 0xfe, 0xc4, 0x9b, 0x26, 0xf3, 0x53, 0x7b,
	0xb8, 0xfb, 0xab, 0x68, 0xb9, 0x1b, 0xff, 0xa3, 0x97, 0x5f, 0xc1, 0x69, 0x7f, 0xe7, 0x9a, 0x2b,
	0x4d, 0x72, 0x18, 0xec, 0xb8, 0xd2, 0xa9, 0x67, 0x5d, 0x8d, 0x8f, 0x5d, 0x15, 0x96, 0xcb, 0x97,
	0x90, 0x2c, 0x1a, 0x64, 0x28, 0x34, 0xa7, 0x3b, 0x45, 0x32, 0x18, 0xed, 0x15, 0x36, 0x66, 0xd4,
	0x9d, 0x87, 0x1e, 0x1b, 0xae, 0xa6, 0x4a, 0x3d, 0xc9, 0x86, 0x59, 0x2f, 0x71, 0xd1, 0xe3, 0xfc,
	0xa7, 0x07, 0x23, 0xe7, 0x89, 0xbc, 0x82, 0x48, 0xa0, 0xde, 0xf4, 0x61, 0x86, 0x02, 0xf5, 0x8a,
	0x91, 0x37, 0x90, 0xb8, 0xce, 0x0d, 0xd7, 0x1e, 0x01, 0xae, 0xb4, 0x62, 0xe4, 0x2d, 0x0c, 0x78,
	0xfd, 0xf8, 0xc1, 0xc6, 0xea, 0x1a, 0x5d, 0xd5, 0x0b, 0x29, 0xb6, 0xbc, 0x2c, 0x2c, 0xd5, 0x49,
	0xae, 0x6d, 0xbe, 0x7f, 0x95, 0x5c, 0x9b, 0x09, 0x56, 0xf4, 0xde, 0xe6, 0x1c, 0x17, 0xe6, 0x33,
	0x4f, 0x21, 0xfa, 0xcc, 0x77, 0xfa, 0xcf, 0x15, 0xcb, 0x87, 0x10, 0xae, 0xcc, 0xf2, 0xe4, 0xdf,
	0x61, 0xe4, 0x8e, 0x31, 0xcb, 0x42, 0x19, 0x6b, 0x50, 0xa9, 0x4e, 0xe9, 0xa0, 0x61, 0x4a, 0xaa,
	0xf1, 0x89, 0x1e, 0x3a, 0xf7, 0x0e, 0x9a, 0x35, 0xaa, 0x1b, 0xdc, 0xf2, 0x67, 0x6b, 0x3e, 0x28,
	0x3a, 0x94, 0x5f, 0x40, 0xf8, 0x4d, 0x3e, 0xa0, 0x30, 0xcb, 0xdc, 0xa6, 0xd8, 0x8d, 0xc4, 0x82,
	0xf9, 0x0f, 0x0f, 0x82, 0x5b, 0x79, 0x4b, 0xde, 0x03, 0xf4, 0xc1, 0x28, 0x92, 0xd8, 0xb6, 0x5a,
	0xcb, 0x19, 0x39, 0x8e, 0xcd, 0x06, 0x7b, 0x09, 0xe1, 0x5a, 0x96, 0x5c, 0x90, 0xb3, 0x96, 0x7c,
	0x09, 0x30, 0x03, 0x5b, 0xb1, 0x77, 0xe6, 0x27, 0xe4, 0x06, 0xa2, 0xb5, 0x2c, 0xe5, 0x5e, 0x93,
	0xf3, 0x59, 0x29, 0x65, 0xb9, 0xc3, 0xf6, 0xe5, 0xdd, 0xed, 0xb7, 0xb3, 0xa5, 0x79, 0x88, 0xd9,
	0x3f, 0xea, 0xf9, 0xc9, 0x5d, 0x64, 0x2b, 0x57, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x68, 0xef,
	0xc3, 0x2a, 0xc2, 0x03, 0x00, 0x00,
}
